# Generated by Django 5.0.6 on 2024-07-01 16:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customuser_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverystatustype',
            name='change_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
