# Generated by Django 5.0.6 on 2024-07-01 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_deliverystatustype_change_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverystatustype',
            name='description',
            field=models.CharField(choices=[('P', 'Pending'), ('T', 'In transit'), ('C', 'Completed')], max_length=45, unique=True),
        ),
        migrations.CreateModel(
            name='DeliveryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=45)),
                ('change_date', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='app.delivery')),
            ],
            options={
                'verbose_name': 'Delivery History',
                'verbose_name_plural': 'Delivery Histories',
                'db_table': 'delivery_history',
            },
        ),
    ]
