# Generated by Django 5.0.6 on 2024-07-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_deliverystatustype_description_deliveryhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverystatustype',
            name='description',
            field=models.CharField(choices=[('P', 'Pending'), ('T', 'In transit'), ('C', 'Completed')], max_length=45),
        ),
    ]
